# Generated by Django 2.0 on 2017-12-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='place',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
