# Generated by Django 2.0 on 2017-12-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_team_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackendAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(blank=True, max_length=200, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='repo_url',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AddField(
            model_name='backendaction',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.BackendAuth'),
        ),
    ]
