# Generated by Django 2.0 on 2017-12-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_auto_20171227_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
