# Generated by Django 2.0 on 2017-12-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_auto_20171227_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='points',
            new_name='points_earned',
        ),
    ]
