# Generated by Django 2.0 on 2017-12-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_auto_20171227_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='points_earned',
            field=models.IntegerField(null=True),
        ),
    ]
