# Generated by Django 2.0 on 2018-01-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='num_pools',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='scenario',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
