# Generated by Django 2.0 on 2018-01-08 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0012_auto_20180108_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchgroup',
            old_name='match_generated',
            new_name='matches_generated',
        ),
    ]
